### ISSUE TITLE
error[E0425]: cannot find value `GIT_VERSION` in module `built_info`

### ISSUE THREAD

**Issue by bbigras** [lukaslueg/built#23]
I just updated to 0.4 and got this. It worked with 0.3.

rustc 1.43.0-nightly (58b834344 2020-02-05)
on Windows
I have git in my PATH.

```
> cargo build
   Compiling some-project v0.1.0 (C:\Users\bbigras\dev\some-project)
error[E0425]: cannot find value `GIT_VERSION` in module `built_info`
    --> src\main.rs:2305:37
     |
2305 |                         built_info::GIT_VERSION
     |                                     ^^^^^^^^^^^ help: a constant with a similar name exists: `PKG_VERSION`
     |
    ::: C:\Users\bbigras\dev\some-project\target\debug\build\some-project-5cad0dd9a82b04a2\out/built.rs:7:1
     |
7    | pub const PKG_VERSION: &str = "0.1.0";
     | -------------------------------------- similarly named constant `PKG_VERSION` defined here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
```

built.rs
```
//
// EVERYTHING BELOW THIS POINT WAS AUTO-GENERATED DURING COMPILATION. DO NOT MODIFY.
//
/// The Continuous Integration platform detected during compilation.
pub const CI_PLATFORM: Option<&str> = None;
#[doc="The full version."]
pub const PKG_VERSION: &str = "0.1.0";
#[doc="The major version."]
pub const PKG_VERSION_MAJOR: &str = "0";
#[doc="The minor version."]
pub const PKG_VERSION_MINOR: &str = "1";
#[doc="The patch version."]
pub const PKG_VERSION_PATCH: &str = "0";
#[doc="The pre-release version."]
pub const PKG_VERSION_PRE: &str = "";
#[doc="A colon-separated list of authors."]
pub const PKG_AUTHORS: &str = "Bruno Bigras <my_email>";
#[doc="The name of the package."]
pub const PKG_NAME: &str = "some-project";
#[doc="The description."]
pub const PKG_DESCRIPTION: &str = "";
#[doc="The homepage."]
pub const PKG_HOMEPAGE: &str = "";
#[doc="The target triple that was being compiled for."]
pub const TARGET: &str = "x86_64-pc-windows-msvc";
#[doc="The host triple of the rust compiler."]
pub const HOST: &str = "x86_64-pc-windows-msvc";
#[doc="`release` for release builds, `debug` for other builds."]
pub const PROFILE: &str = "debug";
#[doc="The compiler that cargo resolved to use."]
pub const RUSTC: &str = "rustc";
#[doc="The documentation generator that cargo resolved to use."]
pub const RUSTDOC: &str = "rustdoc";
#[doc="Value of OPT_LEVEL for the profile used during compilation."]
pub const OPT_LEVEL: &str = "0";
#[doc="The parallelism that was specified during compilation."]
pub const NUM_JOBS: u32 = 2;
#[doc="Value of DEBUG for the profile used during compilation."]
pub const DEBUG: bool = true;
/// The features that were enabled during compilation.
pub const FEATURES: [&str; 0] = [];
/// The features as a comma-separated string.
pub const FEATURES_STR: &str = "";
/// The output of `rustc -V`
pub const RUSTC_VERSION: &str = "rustc 1.43.0-nightly (58b834344 2020-02-05)";
/// The output of `rustdoc -V`
pub const RUSTDOC_VERSION: &str = "rustdoc 1.43.0-nightly (58b834344 2020-02-05)";
/// The target architecture, given by `cfg!(target_arch)`.
pub const CFG_TARGET_ARCH: &str = "x86_64";
/// The endianness, given by `cfg!(target_endian)`.
pub const CFG_ENDIAN: &str = "little";
/// The toolchain-environment, given by `cfg!(target_env)`.
pub const CFG_ENV: &str = "msvc";
/// The OS-family, given by `cfg!(target_family)`.
pub const CFG_FAMILY: &str = "windows";
/// The operating system, given by `cfg!(target_os)`.
pub const CFG_OS: &str = "windows";
/// The pointer width, given by `cfg!(target_pointer_width)`.
pub const CFG_POINTER_WIDTH: &str = "64";
//
// EVERYTHING ABOVE THIS POINT WAS AUTO-GENERATED DURING COMPILATION. DO NOT MODIFY.
//
```

**Comment by bbigras** [comment]
I just had to use `features = [ "git2" ]`

**Comment by lukaslueg** [comment]
yes :)

**Comment by lukaslueg** [comment]
https://docs.rs/built/0.4.0/built/struct.Options.html#method.set_git

**Comment by bbigras** [comment]
Sorry about that. Thanks for the help, and for the package. I use it everywhere.

**Comment by lukaslueg** [comment]
you're welcome
